name: Run tests and deploy application to VPS
on: push
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
        
  deploy:
    needs: run-tests
    runs-on: ubuntu-22.04
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Copy repository contents to vps via scp
        uses: appleboy/scp-action@master
        env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
        with:
          source: .
          target: /home/CD-Assignment/
          
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          script: sh /home/CD-Assignment/commands.sh
