name: Run tests and deploy application to VPS
on: push
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
        
  deploy:
    needs: run-tests
    runs-on: ubuntu-22.04
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Copy repository contents to vps via scp
        uses: appleboy/scp-action@master
        env:
          host: '${{ secrets.HOST }}'
          port: '${{ secrets.PORT }}'
		  username: '${{ secrets.USERNAME }}'
          password: '${{ secrets.PASSWORD }}'
        with:
          source: .
          target: /home/CD-Assignment/
          
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.HOST }}'
          port: '${{ secrets.PORT }}'
		  username: '${{ secrets.USERNAME }}'
          password: '${{ secrets.PASSWORD }}'
          script: sh /home/CD-Assignment/commands.sh
